// this page is for movies constants

export const MOVIES_LIST_REQUEST = "MOVIES_LIST_REQUEST";
export const MOVIES_LIST_SUCCESS = "MOVIES_LIST_SUCCESS";
export const MOVIES_LIST_FAIL = "MOVIES_LIST_FAIL";

export const GET_RANDOM_REQUEST = "GET_RANDOM_REQUEST";
export const GET_RANDOM_SUCCESS = "GET_RANDOM_SUCCESS";
export const GET_RANDOM_FAIL = "GET_RANDOM_FAIL";

export const MOVIE_DETAILS_REQUEST = "MOVIE_DETAILS_REQUEST";
export const MOVIE_DETAILS_SUCCESS = "MOVIE_DETAILS_SUCCESS";
export const MOVIE_DETAILS_FAIL = "MOVIE_DETAILS_FAIL";
export const MOVIE_DETAILS_RESET = "MOVIE_DETAILS_RESET";

export const TOP_RATED_MOVIES_REQUEST = "TOP_RATED_MOVIES_REQUEST";
export const TOP_RATED_MOVIES_SUCCESS = "TOP_RATED_MOVIES_SUCCESS";
export const TOP_RATED_MOVIES_FAIL = "TOP_RATED_MOVIES_FAIL";

export const MOVIE_REVIEW_REQUEST = "MOVIE_REVIEW_REQUEST";
export const MOVIE_REVIEW_SUCCESS = "MOVIE_REVIEW_SUCCESS";
export const MOVIE_REVIEW_FAIL = "MOVIE_REVIEW_FAIL";
export const MOVIE_REVIEW_RESET = "MOVIE_REVIEW_RESET";

export const DELETE_MOVIE_REQUEST = "DELETE_MOVIE_REQUEST";
export const DELETE_MOVIE_SUCCESS = "DELETE_MOVIE_SUCCESS";
export const DELETE_MOVIE_FAIL = "DELETE_MOVIE_FAIL";

export const DELETE_ALL_MOVIES_REQUEST = "DELETE_ALL_MOVIES_REQUEST";
export const DELETE_ALL_MOVIES_SUCCESS = "DELETE_ALL_MOVIES_SUCCESS";
export const DELETE_ALL_MOVIES_FAIL = "DELETE_ALL_MOVIES_FAIL";

export const CREATE_MOVIE_REQUEST = "CREATE_MOVIE_REQUEST";
export const CREATE_MOVIE_SUCCESS = "CREATE_MOVIE_SUCCESS";
export const CREATE_MOVIE_FAIL = "CREATE_MOVIE_FAIL";
export const CREATE_MOVIE_RESET = "CREATE_MOVIE_RESET";

export const ADD_CAST = "ADD_CAST";
export const EDIT_CAST = "EDIT_CAST";
export const DELETE_CAST = "DELETE_CAST";
export const RESET_CAST = "RESET_CAST";

export const UPDATE_MOVIE_REQUEST = "UPDATE_MOVIE_REQUEST";
export const UPDATE_MOVIE_SUCCESS = "UPDATE_MOVIE_SUCCESS";
export const UPDATE_MOVIE_FAIL = "UPDATE_MOVIE_FAIL";
export const UPDATE_MOVIE_RESET = "UPDATE_MOVIE_RESET";

export const DOWNLOAD_MOVIE_REQUEST = "DOWNLOAD_MOVIE_REQUEST";
export const DOWNLOAD_MOVIE_SUCCESS = "DOWNLOAD_MOVIE_SUCCESS";
export const DOWNLOAD_MOVIE_FAIL = "DOWNLOAD_MOVIE_FAIL";
export const DOWNLOAD_MOVIE_RESET = "DOWNLOAD_MOVIE_RESET";
